version: '3'
services:
  apiserver:
    build:
      dockerfile: Dockerfile.dev
      context: ./apiserver
    volumes:
      - /app/node_modules
      - ./apiserver:/app
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  analyzer:
    build:
      dockerfile: Dockerfile.dev
      context: ./analyzer
    ports:
      - '8000:8000'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
